spring.application.name=progettoWSDA
# ===============================
# CONFIGURAZIONE DATASOURCE (DB)
# ===============================
# ?serverTimezone=UTC serve per evitare errori di fuso orario comuni con i driver nuovi.
spring.datasource.url=jdbc:mysql://localhost:3306/hotelmanagement?serverTimezone=UTC

# Credenziali di accesso
spring.datasource.username=root
spring.datasource.password=Tigrosenzapassword30

# Il driver specifico per MySQL (Maven lo ha scaricato grazie alla dipendenza nel pom.xml)
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ===============================
# CONFIGURAZIONE JPA / HIBERNATE
# ===============================
# 'update': Hibernate controlla il DB. Se mancano colonne o tabelle rispetto alle tue classi Java,
# prova ad aggiungerle automaticamente senza cancellare i dati esistenti.
# Se preferisci che NON tocchi nulla, usa 'validate' o 'none'.
spring.jpa.hibernate.ddl-auto=update

# Mostra nella console di IntelliJ le query SQL che Spring fa "di nascosto". Utile per debug
#spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

#setto le credenziali per springboot security
spring.security.user.name=admin
spring.security.user.password=admin
spring.profiles.active=development



#per debug disattivo tutti i print delle query hibernate


# Spegne la stampa delle query (il muro di testo bianco)
spring.jpa.show-sql=false

# Spegne i dettagli dei parametri (il muro di testo coi punti interrogativi)
logging.level.org.hibernate.SQL=OFF
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=OFF